.PHONY: bootstrap analyze test run

APP_DIR := tic_tac_toe_frontend

bootstrap:
\tcd $(APP_DIR) && flutter pub get

analyze:
\tcd $(APP_DIR) && flutter analyze

test:
\tcd $(APP_DIR) && flutter test

run:
\tcd $(APP_DIR) && flutter run
